version: "3.9"
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    image: mankiprimat/todoassistent:last

  todo:
    image: mankiprimat/todoassistent:last
    depends_on:
      - master
    command: ["sh", "./start.sh"]
    environment:
      - MODULE=todo-service
      - PORT=3000
    ports:
      - "3000:3000"
  auth-jwt:
    image: mankiprimat/todoassistent:last
    depends_on:
      - master
    command: ["sh", "./start.sh"]
    environment:
      - MODULE=auth-jwt-service
      - PORT=3001
    ports:
      - "3001:3001"
  mongodb:
    image: "mongo:latest"
    volumes:
      - /var/data/mongodb:/data/db
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"


