###
GET  http://localhost:3000
Content-Type: application/json
Authorization: Bearer {{accessTokenEndless}}


{
  "title": "test_Relaxation_?"
}

###
GET  http://localhost:3003
Content-Type: application/json
Authorization: Bearer {{accessTokenEndless}}

###
POST  http://localhost:3000
Content-Type: application/json
Authorization: Bearer {{accessTokenEndless}}

{
  "title": "test",
  "description": "beschreibung..."
}

###
POST  http://localhost:3000
Content-Type: application/json
Authorization: Bearer {{accessTokenEndless}}

  [
    {
      "title": "testA",
      "description": "beschreibung..."
    },
    {
      "title": "testB",
      "description": "beschreibung..."
    }
  ]


###
PUT  http://localhost:3000
Content-Type: application/json

{
  "_id": "6081d42884fd65334c6c1333",
  "title": "test23",
  "description": "beschreibungX2..."
}

###
DELETE http://localhost:3000
Content-Type: application/json

{
  "_id": "60832fb4f85faf0dd8cebca3"
}

###
POST http://localhost:3001/token
Content-Type: application/json


{
  "username": "user",
  "password": ""
}
