###TemplateV1
POST  http://localhost:3000
Content-Type: application/json
Authorization: Bearer {{accessTokenEndless}}

[
  {
    "title": "test_Template_Routine_0",
    "category": "Routine",
    "priority": 1,
    "description": "Quis veniam tempor ad sunt mollit in. Officia laborum aliqua magna veniam cillum excepteur laborum reprehenderit commodo laboris. Pariatur occaecat anim ullamco ipsum eiusmod anim nulla qui elit eu ex sit.",
    "templatePeriod": 1,
    "isTemplate": true
  },
  {
    "title": "test_Template_Routine_1",
    "category": "Routine",
    "priority": 0,
    "description": "Dolore esse tempor duis veniam Lorem fugiat nostrud eiusmod. Veniam ullamco velit nostrud ipsum qui sint. Adipisicing velit aute incididunt dolore nulla incididunt occaecat pariatur consectetur quis esse.",
    "templatePeriod": 2,
    "isTemplate": true
  },
  {
    "title": "test_Routine_0",
    "category": "Routine",
    "status": "todo",
    "priority": 1,
    "description": "Dolor velit elit non sunt voluptate sit proident cillum anim. Ea exercitation ullamco deserunt proident consectetur id commodo nulla laboris occaecat sunt. Laborum nisi proident cupidatat eu et fugiat ullamco.",
    "isTemplate": false
  },
  {
    "title": "test_Routine_1",
    "category": "Routine",
    "status": "todo",
    "priority": 2,
    "description": "Deserunt pariatur incididunt Lorem aliqua sit ipsum exercitation proident commodo proident. Exercitation aliqua consequat reprehenderit anim. Exercitation mollit aute ut laborum excepteur consectetur adipisicing cillum qui consectetur.",
    "isTemplate": false
  }
]

###V1:
POST  http://localhost:3000
Content-Type: application/json
Authorization: Bearer {{accessTokenEndless}}

[
  {
    "title": "test_Routine_0",
    "category": "Routine",
    "latestFinish": "Fri Sep 24 2021 08:34:08 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 0,
    "description": "Fugiat occaecat cillum minim occaecat eiusmod sunt. Amet et do eu adipisicing. Minim nisi excepteur minim cupidatat adipisicing sint ipsum."
  },
  {
    "title": "test_Routine_1",
    "category": "Routine",
    "latestFinish": "Thu Sep 23 2021 13:26:36 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 0,
    "description": "Aliquip aute duis anim esse ut ex qui eu deserunt aliqua ad laboris ut velit. Excepteur deserunt ut exercitation reprehenderit culpa tempor incididunt qui. Enim est duis voluptate qui cupidatat in."
  },
  {
    "title": "test_Routine_2",
    "category": "Routine",
    "latestFinish": "Thu Sep 23 2021 15:32:49 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 2,
    "description": "Eiusmod do eu cupidatat tempor irure reprehenderit ut ex do ea laborum anim reprehenderit. Ullamco dolore sint dolore qui. Incididunt ea veniam incididunt laboris nisi laborum aliquip fugiat."
  },
  {
    "title": "test_Important_0",
    "category": "Important",
    "latestFinish": "Tue Jul 20 2021 04:48:06 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 0,
    "description": "Non do consequat voluptate irure anim deserunt. Nisi voluptate pariatur consectetur est non aute sint ea qui. Ex sunt anim deserunt est aliqua sit elit et minim magna eu id laborum."
  },
  {
    "title": "test_Important_1",
    "category": "Important",
    "latestFinish": "Thu Aug 05 2021 10:05:37 GMT+0000 (UTC)",
    "status": "todo",
    "priority": "-1",
    "description": "Ipsum enim laboris est fugiat enim Lorem velit minim nulla culpa sint. Qui aliquip ut amet officia eiusmod tempor dolore qui. Anim in irure ullamco ad fugiat nostrud."
  },
  {
    "title": "test_Important_2",
    "category": "Important",
    "latestFinish": "Sat Jul 03 2021 08:19:12 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 0,
    "description": "Magna reprehenderit laboris sit do elit aliqua irure est. Qui esse veniam incididunt culpa non veniam anim nisi est laboris enim. Proident qui laboris voluptate fugiat ex adipisicing tempor elit fugiat."
  },
  {
    "title": "test_Important_3",
    "category": "Important",
    "latestFinish": "Wed Aug 18 2021 23:36:17 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 2,
    "description": "Amet reprehenderit laborum ex veniam occaecat elit elit ea. Dolor magna velit qui cillum aliqua et labore irure elit. Dolor pariatur enim laboris exercitation."
  },
  {
    "title": "test_Pastime_0",
    "category": "Pastime",
    "latestFinish": "Fri Jun 04 2021 19:52:33 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 0,
    "description": "Aute eiusmod exercitation minim elit. Quis mollit in non cupidatat laborum dolore sint exercitation occaecat laborum ad fugiat reprehenderit magna. Et culpa dolore elit esse sunt laborum laborum tempor magna consectetur."
  },
  {
    "title": "test_Pastime_1",
    "category": "Pastime",
    "latestFinish": "Tue May 11 2021 20:59:49 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 0,
    "description": "Minim occaecat excepteur aliqua aute adipisicing esse sunt dolor tempor nulla laborum. Magna mollit do magna nostrud labore tempor fugiat aute voluptate ipsum. Laboris nostrud occaecat enim est labore in incididunt minim eu."
  },
  {
    "title": "test_Pastime_2",
    "category": "Pastime",
    "latestFinish": "Thu Sep 23 2021 16:24:30 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 2,
    "description": "Ea labore consequat eu pariatur ex adipisicing adipisicing nulla pariatur tempor. Minim proident laboris aliqua magna id ad mollit ex laboris. Dolore ut adipisicing velit duis minim quis sint culpa ad occaecat veniam commodo pariatur."
  },
  {
    "title": "test_Pastime_3",
    "category": "Pastime",
    "latestFinish": "Sat Aug 28 2021 10:07:00 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 2,
    "description": "Deserunt irure irure et pariatur. Pariatur proident qui do velit est nisi. Occaecat ea aute elit pariatur deserunt laborum exercitation duis do."
  },
  {
    "title": "test_Pastime_4",
    "category": "Pastime",
    "latestFinish": "Wed Sep 22 2021 11:53:11 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 0,
    "description": "Eu est labore aliquip fugiat ullamco esse ad tempor amet adipisicing laboris. Mollit proident do cillum reprehenderit labore magna cupidatat. Dolore aliqua dolor aute do laborum ullamco magna eu deserunt aliqua deserunt."
  },
  {
    "title": "test_Relaxation_0",
    "category": "Relaxation",
    "latestFinish": "Wed Jun 16 2021 15:56:20 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 1,
    "description": "Minim quis nostrud aliquip mollit cillum officia. Sunt adipisicing est aute incididunt amet labore mollit anim sunt pariatur ex voluptate. Minim officia mollit occaecat esse id nostrud mollit."
  },
  {
    "title": "test_Relaxation_1",
    "category": "Relaxation",
    "latestFinish": "Sun May 09 2021 12:31:10 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 1,
    "description": "Veniam dolore eu amet incididunt veniam ex consequat Lorem excepteur duis cupidatat magna. Irure magna reprehenderit quis minim ea eu velit cillum culpa consectetur magna culpa eu minim. Mollit ex officia nulla nisi minim veniam irure mollit cillum magna laborum enim dolor minim."
  },
  {
    "title": "test_Relaxation_2",
    "category": "Relaxation",
    "latestFinish": "Sun Sep 12 2021 04:50:08 GMT+0000 (UTC)",
    "status": "todo",
    "priority": "-1",
    "description": "Culpa consequat pariatur dolor eiusmod labore Lorem amet nisi irure cillum elit eiusmod adipisicing. Commodo in exercitation irure sit pariatur voluptate ea voluptate enim velit. Nostrud non exercitation non nulla id ipsum mollit anim deserunt."
  },
  {
    "title": "test_Relaxation_3",
    "category": "Relaxation",
    "latestFinish": "Fri Aug 06 2021 00:08:40 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 0,
    "description": "Eu et consequat irure id ex. Dolore anim consequat fugiat mollit minim culpa sunt ut voluptate sit commodo cupidatat reprehenderit pariatur. Officia sunt fugiat amet Lorem aliqua magna proident et anim dolor velit Lorem sunt qui."
  },
  {
    "title": "test_Relaxation_4",
    "category": "Relaxation",
    "latestFinish": "Fri Jun 11 2021 08:29:27 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 2,
    "description": "In Lorem dolore minim id fugiat aliqua elit occaecat reprehenderit. Quis id labore ipsum sint non incididunt excepteur. Velit minim ea occaecat ea ex reprehenderit eu in duis et id Lorem."
  },
  {
    "title": "test_SocialContact_0",
    "category": "SocialContact",
    "latestFinish": "Tue Sep 14 2021 09:46:49 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 1,
    "description": "Nulla cupidatat esse eu nisi cupidatat duis adipisicing anim mollit velit incididunt ullamco adipisicing. Ad occaecat occaecat mollit incididunt amet amet est voluptate dolore deserunt pariatur laboris fugiat. Ut ad id consectetur reprehenderit duis dolor elit ipsum."
  },
  {
    "title": "test_SocialContact_1",
    "category": "SocialContact",
    "latestFinish": "Sun Sep 05 2021 00:40:49 GMT+0000 (UTC)",
    "status": "todo",
    "priority": "-1",
    "description": "Do commodo aliquip commodo ut culpa voluptate excepteur. Sunt Lorem ullamco labore non. Esse exercitation ipsum quis excepteur ullamco."
  },
  {
    "title": "test_SocialContact_2",
    "category": "SocialContact",
    "latestFinish": "Tue Sep 14 2021 02:08:45 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 1,
    "description": "Sunt consectetur est et ipsum aute sint non ut. Est occaecat laboris pariatur minim aute et voluptate occaecat. Reprehenderit eiusmod dolor culpa reprehenderit velit qui amet veniam occaecat."
  },
  {
    "title": "test_SocialContact_3",
    "category": "SocialContact",
    "latestFinish": "Mon Sep 27 2021 12:48:30 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 1,
    "description": "Est pariatur deserunt aliquip tempor velit. Adipisicing elit elit pariatur occaecat occaecat sit minim laboris ex consequat velit in pariatur consectetur. Cillum excepteur in consectetur elit et et pariatur voluptate veniam veniam tempor est occaecat ad."
  },
  {
    "title": "test_SocialContact_4",
    "category": "SocialContact",
    "latestFinish": "Mon May 24 2021 02:12:33 GMT+0000 (UTC)",
    "status": "todo",
    "priority": "-1",
    "description": "Nulla sunt minim nulla aliquip voluptate amet sunt veniam sunt. Esse sint pariatur laboris ipsum non velit deserunt consequat est qui sint. Sint occaecat ex ea aliqua minim laborum voluptate est Lorem velit minim dolore ex et."
  },
  {
    "title": "test_SocialContact_5",
    "category": "SocialContact",
    "latestFinish": "Tue Sep 14 2021 13:01:39 GMT+0000 (UTC)",
    "status": "todo",
    "priority": 0,
    "description": "Sit sunt sit amet mollit quis ut amet pariatur nulla amet. Aliqua elit elit amet elit et enim consequat eiusmod eu reprehenderit occaecat. Ad nostrud fugiat pariatur elit."
  }
]
